### ISSUE TITLE
Update Volunteer Timeline

### ISSUE THREAD

**Issue by norsehorse89** [socallinuxexpo/scale-av-web#33]
Volunteer timeline on scale-av minimalist webpage should read as follows:

Mar 7/8 (Tues night,Wed)... instead of ~~Mar 3/4~~

Mar 9-12 (Thu-Sun)... instead of ~~Mar 5-8~~

Mar 12 (Sun)... instead of ~~Mar 8~~

**Comment by ldang** [comment]
My goal is to update the scale-av minmimalist webpage to be timeless, so we never have to update it.
